name: firebase_recipe_app
description: A simple Recipe Book app demonstrating CRUD with Firebase Firestore.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.7.0
  flutter_slidable: ^2.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/